[2022-08-11 17:22:09,431] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.gzip scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2022-08-11 17:22:09,469] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.gzip scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2022-08-11 17:22:09,470] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 17:22:09,472] {taskinstance.py:1239} INFO - Starting attempt 7 of 7
[2022-08-11 17:22:09,473] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 17:22:09,511] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): gzip> on 2022-01-02 06:00:00+00:00
[2022-08-11 17:22:09,517] {standard_task_runner.py:52} INFO - Started process 6180 to run task
[2022-08-11 17:22:09,523] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'gzip', 'scheduled__2022-01-02T06:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp_e01os7k', '--error-file', '/tmp/tmpet7pro78']
[2022-08-11 17:22:09,526] {standard_task_runner.py:77} INFO - Job 52: Subtask gzip
[2022-08-11 17:22:09,647] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.gzip scheduled__2022-01-02T06:00:00+00:00 [running]> on host cdc85d7e6248
[2022-08-11 17:22:09,782] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-08-11 17:22:09,818] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=gzip
AIRFLOW_CTX_EXECUTION_DATE=2022-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-02T06:00:00+00:00
[2022-08-11 17:22:09,822] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-11 17:22:09,824] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'gunzip /opt/***/output_2021-01.csv.gz']
[2022-08-11 17:22:09,836] {subprocess.py:85} INFO - Output:
[2022-08-11 17:22:09,917] {subprocess.py:89} INFO - 
[2022-08-11 17:22:09,919] {subprocess.py:89} INFO - gzip: /opt/***/output_2021-01.csv.gz: not in gzip format
[2022-08-11 17:22:09,922] {subprocess.py:93} INFO - Command exited with return code 1
[2022-08-11 17:22:09,961] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-08-11 17:22:09,992] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=gzip, execution_date=20220102T060000, start_date=20220811T172209, end_date=20220811T172209
[2022-08-11 17:22:10,036] {standard_task_runner.py:92} ERROR - Failed to execute job 52 for task gzip
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-08-11 17:22:10,063] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-08-11 17:22:10,172] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
