[2022-08-11 20:17:12,059] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.gzip scheduled__2022-08-10T00:00:00+00:00 [queued]>
[2022-08-11 20:17:12,168] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.gzip scheduled__2022-08-10T00:00:00+00:00 [queued]>
[2022-08-11 20:17:12,182] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 20:17:12,189] {taskinstance.py:1239} INFO - Starting attempt 2 of 3
[2022-08-11 20:17:12,194] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 20:17:12,320] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): gzip> on 2022-08-10 00:00:00+00:00
[2022-08-11 20:17:12,368] {standard_task_runner.py:52} INFO - Started process 1036 to run task
[2022-08-11 20:17:12,392] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'gzip', 'scheduled__2022-08-10T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gpc.py', '--cfg-path', '/tmp/tmpfi7ahbc1', '--error-file', '/tmp/tmpa33_bdht']
[2022-08-11 20:17:12,399] {standard_task_runner.py:77} INFO - Job 83: Subtask gzip
[2022-08-11 20:17:12,683] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.gzip scheduled__2022-08-10T00:00:00+00:00 [running]> on host a96959784c93
[2022-08-11 20:17:12,951] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=gzip
AIRFLOW_CTX_EXECUTION_DATE=2022-08-10T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-10T00:00:00+00:00
[2022-08-11 20:17:12,958] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-11 20:17:12,966] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'gunzip /opt/***/yellow_tripdata_2021-01.csv.gz']
[2022-08-11 20:17:13,005] {subprocess.py:85} INFO - Output:
[2022-08-11 20:17:13,093] {subprocess.py:89} INFO - gzip: /opt/***/yellow_tripdata_2021-01.csv already exists;	not overwritten
[2022-08-11 20:17:13,097] {subprocess.py:93} INFO - Command exited with return code 2
[2022-08-11 20:17:13,136] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-08-11 20:17:13,192] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=gzip, execution_date=20220810T000000, start_date=20220811T201712, end_date=20220811T201713
[2022-08-11 20:17:13,247] {standard_task_runner.py:92} ERROR - Failed to execute job 83 for task gzip
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-08-11 20:17:13,294] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-08-11 20:17:13,428] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
