[2022-08-11 18:54:08,819] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.gzip scheduled__2022-05-02T06:00:00+00:00 [queued]>
[2022-08-11 18:54:08,865] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.gzip scheduled__2022-05-02T06:00:00+00:00 [queued]>
[2022-08-11 18:54:08,867] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 18:54:08,869] {taskinstance.py:1239} INFO - Starting attempt 5 of 5
[2022-08-11 18:54:08,870] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 18:54:08,921] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): gzip> on 2022-05-02 06:00:00+00:00
[2022-08-11 18:54:08,940] {standard_task_runner.py:52} INFO - Started process 2761 to run task
[2022-08-11 18:54:08,951] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'gzip', 'scheduled__2022-05-02T06:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpsqv4tm4v', '--error-file', '/tmp/tmphxuj0ezr']
[2022-08-11 18:54:08,955] {standard_task_runner.py:77} INFO - Job 70: Subtask gzip
[2022-08-11 18:54:09,142] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.gzip scheduled__2022-05-02T06:00:00+00:00 [running]> on host 3b421e1efda7
[2022-08-11 18:54:09,356] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-08-11 18:54:09,436] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=gzip
AIRFLOW_CTX_EXECUTION_DATE=2022-05-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-02T06:00:00+00:00
[2022-08-11 18:54:09,447] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-11 18:54:09,451] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'gunzip /opt/***/output_2021-05.csv.gz']
[2022-08-11 18:54:09,485] {subprocess.py:85} INFO - Output:
[2022-08-11 18:54:09,610] {subprocess.py:89} INFO - gzip: /opt/***/output_2021-05.csv.gz: No such file or directory
[2022-08-11 18:54:09,619] {subprocess.py:93} INFO - Command exited with return code 1
[2022-08-11 18:54:09,696] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-08-11 18:54:09,739] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=gzip, execution_date=20220502T060000, start_date=20220811T185408, end_date=20220811T185409
[2022-08-11 18:54:09,813] {standard_task_runner.py:92} ERROR - Failed to execute job 70 for task gzip
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-08-11 18:54:09,856] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-08-11 18:54:09,994] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
