[2022-08-11 20:29:40,522] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.gzip manual__2022-08-11T20:09:33.322468+00:00 [queued]>
[2022-08-11 20:29:40,605] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.gzip manual__2022-08-11T20:09:33.322468+00:00 [queued]>
[2022-08-11 20:29:40,610] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 20:29:40,614] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-08-11 20:29:40,618] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 20:29:40,747] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): gzip> on 2022-08-11 20:09:33.322468+00:00
[2022-08-11 20:29:40,799] {standard_task_runner.py:52} INFO - Started process 2030 to run task
[2022-08-11 20:29:40,817] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'gzip', 'manual__2022-08-11T20:09:33.322468+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gpc.py', '--cfg-path', '/tmp/tmpaiwji42i', '--error-file', '/tmp/tmpu_q9vvqn']
[2022-08-11 20:29:40,829] {standard_task_runner.py:77} INFO - Job 96: Subtask gzip
[2022-08-11 20:29:41,425] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.gzip manual__2022-08-11T20:09:33.322468+00:00 [running]> on host a96959784c93
[2022-08-11 20:29:41,710] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=gzip
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T20:09:33.322468+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T20:09:33.322468+00:00
[2022-08-11 20:29:41,720] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-11 20:29:41,728] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'gunzip /opt/***/yellow_tripdata_2021-02.csv.gz']
[2022-08-11 20:29:41,766] {subprocess.py:85} INFO - Output:
[2022-08-11 20:29:41,876] {subprocess.py:89} INFO - gzip: /opt/***/yellow_tripdata_2021-02.csv already exists;	not overwritten
[2022-08-11 20:29:41,884] {subprocess.py:93} INFO - Command exited with return code 2
[2022-08-11 20:29:41,987] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-08-11 20:29:42,076] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=gzip, execution_date=20220811T200933, start_date=20220811T202940, end_date=20220811T202942
[2022-08-11 20:29:42,177] {standard_task_runner.py:92} ERROR - Failed to execute job 96 for task gzip
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-08-11 20:29:42,259] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-08-11 20:29:42,611] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
